all:	test-sorted-ll set-on-sorted-ll set-on-sorted-ll-solns

test-sorted-ll: test-sorted-ll.c sorted-ll.c sorted-ll.h
	gcc -o test-sorted-ll test-sorted-ll.c sorted-ll.c -I.

set-on-sorted-ll: set-on-sorted-ll.c sorted-ll.c sorted-ll.h
	gcc -o set-on-sorted-ll set-on-sorted-ll.c sorted-ll.c -I.

